spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mars
    driver-class-name: com.mysql.cj.jdbc.Driver

#    show sql and format
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181